ShinyMaterial/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'ShinyMaterial'
urlpatterns = [
    path('', views.home, name='home'),
    path('videos/', views.videos, name='video'),
    # Forum
    path('forum/', views.forum_view, name='forum'),
    path('forum/comment/', views.comment_view, name='comment'),
    path('forum/create', views.forum_create, name='create'),
    path('forum/search/', views.search_post, name='message_search'),
    path('forum/filter', views.advfilter, name='advfilter'),
    path('forum/searchworker/', views.searchworker_view, name='searchworker'),
    # Forum End
    path('posts/', views.posts, name='posts'),
    path('about/', views.about, name='about'),
    # Prole
    path('profile/', views.profile_view, name='profile'),
    path('profile/fa/', views.fa, name='fa'),
    path('profileadd', views.profile_add, name='profile_add'),
    path('notification', views.notification_view, name='notification'),
    path('settings', views.settings_view, name='settings'),
    # Account
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # Old Site
    path('sale/', views.sale, name='sale'),
    # For Supporter
    path('supporter/', views.supporter, name='supporter'),
    # Help
    path('problems', views.problems, name='problem'),
    # Rickroll
    path('tests', views.rickroll, name='rickroll')
]

ShinyMaterialSite/urls.py
from django.contrib import admin
from django.urls import path, include
from ShinyMaterial import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShinyMaterial.urls'))
]

templates/about.html
<!DOCTYPE html>
{% load static %}
{% load sass_tags %}
<html>
    <head>
        <title>
            Shiny Material / Developer
        </title>
        <link rel="stylesheet" href="{% static 'css/contacts.css' %}">
		<link rel="icon" href="{% static 'img/Solar_dust.png' %}" />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% sass_src 'css/light/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/mobile/global.scss' %}">
        <!-- Top-Banner Light & Dark -->
        <link rel="stylesheet" href="{% sass_src 'css/light/top-banner.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/top-banner.scss' %}">
        <!--End of scss-->

        <script src="{% static 'js/ddMenu.js' %}"></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
            {% include 'top-banner.html' %}

                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Developer</b></label><br>
                    <span>
                        <li><a class='conlink' href="https://github.com/RestytheCake/">Resty</a></li>
                        <li><a class='conlink' href="https://github.com/RestytheCake/">Morganischkalt</a></li>
                    </span>
                </div>

                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23,140,148);"><b>Source Code</b></label><br>
                    <span style="padding-tleft: 20">
                        <li><a class='conlink' href="https://github.com/RestytheCake/Shiny_Material">GitHub - Mod Source Code</a></li>
                        <li><a class='conlink' href="https://github.com/RestytheCake/ShinyMaterialSite">GitHub - Site Source Code</a></li>

                    </span>
                </div>

                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Found an Issue or have Problems?</b></label><br>
                    <span style="padding-left: 20px">
                        <li><a href="https://github.com/RestytheCake/Shiny_Material/issues">Mod - Issue</a></li>
                        <li><a href="https://github.com/RestytheCake/ShinyMaterialSite/issues">Site - Issue</a></li>
                    </span>
                </div>
    </body>
</html>

templates/home.html
{% load static %}
{% load sass_tags %}
<html lang="en">
    <head>
        <title>
            Shiny Material
        </title>
        <!-- Global light & Dark | Mobile -->
        <link rel="stylesheet" href="{% sass_src 'css/light/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/global.scss' %}">
		<link rel="stylesheet" href="{% sass_src 'css/mobile/global.scss' %}">
        <!-- Top-Banner Light & Dark | Mobile -->
        <link rel="stylesheet" href="{% sass_src 'css/light/top-banner.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/top-banner.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/mobile/top-banner.scss' %}">
        <!-- Icon -->
        <link rel="icon" href="{% static 'img/Solar_dust.png' %}" />
        <!-- Meta data -->
        <meta name="viewport" content="width=device-width"/>
        <meta name="theme-color" content="#4285f4"/>
        <meta name="description" content="Shiny Material WebSite">
        <!-- JS -->
        <script src="{% static 'js/ddMenu.js' %}"></script>
    </head>
    <!--Hardcore starts from here-->
   <body>
   <!-- Top-Banner HTML-->
   {% include 'top-banner.html' %}

   <!-- Post / Some Information in Main Page -->
   <div class="post">
       <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>Short Info</b></label><br>
       <span class="thx"> ShinyMaterial is a Mod which will add :
           <li>Ore's - New Strong and Hard to craft Ore's</li>
           <li>Tools - New Tools stronger then default weapons</li>
           <li>Armor - New Armor which can last longer</li>
           <li>Structure's - New generated Structure's in the Nether</li>
           <li>food - New food with Special Effects</li>

       </span>
   </div>

   <div class="post">
       <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>Last Update</b></label><br>
       <span>Added New Structure to the Nether</span>
   </div>
   
   <!-- Information Ends Here -->
   </body>
</html>

templates/posts.html
<!DOCTYPE html>
{% load sass_tags %}
{% load static %}
<html>
    <head>
        <title>
            Shiny Material / Posts
        </title>
        <link rel="stylesheet" href="{% static 'css/nick.css' %}">
		<link rel="icon" href="{% static 'img/Solar_dust.png' %}" />
        <!--Global light & dark & mobile -->
        <link rel="stylesheet" href="{% sass_src 'css/light/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/mobile/global.scss' %}">
        <!-- Top-Banner Light & Dark -->
        <link rel="stylesheet" href="{% sass_src 'css/light/top-banner.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/top-banner.scss' %}">
        <!--End of scss-->

        <script src="{% static 'js/ddMenu.js' %}"></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
        {% include 'top-banner.html' %}
            <div class="main">
                <form action="{% url 'ShinyMaterial:searchworker' %}" method="get">
                <div id="search">
                    <input type="search" name="User" id="searchBar" placeholder="Quick Search">
                    <button type="submit" id="searchButton"><img  style="width: 25px; height: 25px;" src="{% static 'img/search.png' %}"></button>
                </div>
            </form>
                <div class="post">
                    <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b></b></label><br>
                        <span>
                            Nothing was posted here
                        </span>
                </div>
            </div>
    </body>

templates/testfile.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/top-banner.html
{% load static %}
<div id="topBanner">
    <div>
        {% if request.user.is_authenticated %}
            <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                <label onclick="ddMenu()">{{ request.user.username }}</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ShinyMaterial:profile' %}?user={{ request.user.username }}" style="float: left;">Profile</a>
                    <a href="{% url 'ShinyMaterial:notification' %}" style="float: left;">Notification</a>
                    <a href="{% url 'ShinyMaterial:settings' %}" style="float: left;">Settings</a>
                    <a href="{% url 'ShinyMaterial:logout' %}" style="float: left;">Logout</a>
                </div>
            </div>
        {% else %}
            <div id="dropdown"  style="float: right; margin-right: 70px; margin-top: 20px">
                <label onclick="ddMenu()">New ?</label>
                <div  id="dropdown-content">
                    <a href="{% url 'ShinyMaterial:register' %}" style="float: left;">Register</a>
                    <a href="{% url 'ShinyMaterial:logout' %}" style="float: left;">Login</a>
                </div>
            </div>
        {% endif %}
    </div>
</div>
<!-- Buttons for Top-Banner -->
<div id="scroll">
    <button class="buttonTop" onClick="window.location='{% url 'ShinyMaterial:home' %}';">Home</button>
    <button class="buttonTop" onClick="window.location='{% url 'ShinyMaterial:video' %}';">Videos</button>
    <button class="buttonTop" onClick="window.location='{% url 'ShinyMaterial:forum' %}';">Forum</button>
    <button class="buttonTop" onClick="window.location='{% url 'ShinyMaterial:posts' %}';">Post</button>
    <button class="buttonTop" onClick="window.location='{% url 'ShinyMaterial:about' %}';">Developer</button>
</div>
<!-- End for Buttons -->

templates/videos.html
{% load sass_tags %}
{% load static %}
<html lang="en">
    <head>
        <title>
            Shiny Material / Videos
        </title>
        <!-- Global Light & Dark & Mobile-->
        <link rel="stylesheet" href="{% sass_src 'css/light/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/global.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/mobile/global.scss' %}">
        <!-- Videos Light & Dark-->
        <link rel="stylesheet" href="{% sass_src 'css/light/video.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/video.scss' %}">
        <!-- Top-Banner Light & Dark -->
        <link rel="stylesheet" href="{% sass_src 'css/light/top-banner.scss' %}">
        <link rel="stylesheet" href="{% sass_src 'css/dark/top-banner.scss' %}">
        <!-- Icon -->
		<link rel="icon" href="{% static 'img/Solar_dust.png' %}" />

        <meta name="viewport" content="width=device-width">
        <!-- JS -->
        <script src="{%  static 'js/ddMenu.js' %}"></script>
    </head>
    <!--Hardcore starts from here-->
    <body>
    {% include 'top-banner.html' %}

    <div class="main">
        <div class="post">
            <label style="font-size: 24px; padding: 3px; color:rgb(23, 140, 148);"><b>Most  Viewed  Video</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class='video' src="https://www.youtube.com/embed/W2MXIjjDJxA" frameborder="0" allow="accelerometer; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/RAL-EUMcDU8" frameborder="0" allow="accelerometer; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color:rgb(23, 140, 148);"><b>Character</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/W2MXIjjDJxA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/UiCoMNXEwkQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/RAL-EUMcDU8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Boss Guide</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/qw7USpop87I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/HWLhcvj7eb4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/DWyRLVjNxBY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/JUvmfMyLGxc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Tip and Tricks</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/AY8zYMIRJQk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/ExZk8XE2734" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/7Wn7kUqPld0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
        <div class="post">
            <label style="font-size: 24px; padding: 10px; color: rgb(23, 140, 148);"><b>Damage.mp4</b></label><br>
            <span>
                <hr>
                <div class="video-scroll">
                    <iframe class="video" src="https://www.youtube.com/embed/xTQ1VygFLtM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/_-IMRDcDf4k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <iframe class="video" src="https://www.youtube.com/embed/7c-GOcR3bAk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </span>
        </div>
    </div>
    </body>
</html>